version: "3.1"

services:
  db:
    image: postgres:13-alpine
    container_name: temp-name
    command: postgres -c log_destination=stderr -c log_statement=all
    logging:
      options:
        max-size: "10k"
        max-file: "5"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
